# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180404_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='error',
            name='locationX',
        ),
        migrations.RemoveField(
            model_name='error',
            name='locationY',
        ),
        migrations.AddField(
            model_name='error',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
