# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180419_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioninfo',
            name='horizontalEpsg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collectioninfo',
            name='verticalEpsg',
            field=models.IntegerField(null=True),
        ),
    ]
