version: "3.3"

services: 
  db:
    image: postgres
  django-apache2:
    build: .
    container_name: django-apache2
    ports:
      - '8005:80'
      - '3500:3500'
      - '8006:81'
    volumes: 
      - ./www:/var/www/html
    depends_on:
      - db
