# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-04 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('complete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ChecklistCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PointCloudClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificationId', models.IntegerField(null=True)),
                ('classificationType', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('project_date_received', models.DateTimeField(null=True)),
                ('project_date_assigned', models.DateTimeField(null=True)),
                ('project_completion_date', models.DateTimeField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('absVaAccept', models.BooleanField(default=False)),
                ('relVaAccept', models.NullBooleanField(default=False)),
                ('metadataAccept', models.NullBooleanField(default=False)),
                ('breaklinesAccept', models.NullBooleanField(default=False)),
                ('reportsAccept', models.NullBooleanField(default=False)),
                ('otherAccept', models.NullBooleanField(default=False)),
                ('demAccept', models.NullBooleanField(default=False)),
                ('swathAccept', models.NullBooleanField(default=False)),
                ('classifiedAccept', models.NullBooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProgressChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.BooleanField(default=False)),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Review')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensorUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('workPackageId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('vendor', models.CharField(max_length=200, null=True)),
                ('poc', models.CharField(max_length=200, null=True)),
                ('pocEmail', models.CharField(max_length=200, null=True)),
                ('restrictions', models.NullBooleanField()),
                ('restrictionsDate', models.DateField(null=True)),
                ('restrictionsLayer', models.NullBooleanField()),
                ('thirdPartyQa', models.NullBooleanField()),
                ('thirdPartyQaBy', models.CharField(max_length=200, null=True)),
                ('receivedDate', models.DateField(null=True)),
                ('assignedDate', models.DateField(null=True)),
                ('projectSpec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ProjectSpecification')),
            ],
        ),
        migrations.AddField(
            model_name='pointcloudclassification',
            name='workPackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkPackage'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ReviewProgressChecklist'),
        ),
    ]
